name: image_carousel
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Thomasssb1/image_carousel

environment:
  sdk: ">=2.19.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  image: ^4.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
